version: '3.7'
services:
  db:
    image: mysql:8
    ports:
      - '3306:3306'
    restart: 'unless-stopped'
    volumes:
      - system-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hoplin1234!
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=dev-team
networks:
  system:
    driver: bridge
volumes:
  system-db:
    external: false
