name: CI-Production-Dockerize
on:
  push:
    branches:
      - production
run-name: Dockerize of production version. Triggerd by ${{github.actor}}
jobs:
  dockerize:
    name: Dockerize and upload
    runs-on: ubuntu-latest
    steps:
      # Checkout repository code
      - name: Repository Checkout
        uses: actions/checkout@v4
      # Set Node.js version environment
      - name: Node.js version 18 Environment setting
        uses: actions/setup-node@v4
        with:
          node-version: 18
      # Install dependencies
      - name: Install Dependencies
        run: npm install --force
      - name: Check Build Status
        run: npm run build
      - name: Setup QEMU for multiplatform build
        uses: docker/setup-qemu-action@v3
      - name: Setup docker buildx and set platform
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: hoplin-dev/online-judge:latest
          platforms: linux/amd64,linux/arm64
